import * as React from "react"
import { cn } from "@/lib/utils"
import { Callout } from "@/components/callout"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { CopyButton } from "@/components/copy-button"
import { Mermaid } from "@/components/mermaid"
import { Icon } from "@/components/icon"

const extractText = (node: React.ReactNode): string => {
  if (node == null) return ""
  if (typeof node === "string" || typeof node === "number") return String(node)
  if (Array.isArray(node)) return node.map(extractText).join("")
  if (React.isValidElement(node)) return extractText((node.props as any).children)
  return ""
}

export const components = {
  h1: ({ className, ...props }: React.HTMLAttributes<HTMLHeadingElement>) => (
    <h1
      className={cn(
        "mt-2 scroll-m-20 text-4xl font-bold tracking-tight",
        className
      )}
      {...props}
    />
  ),
  h2: ({ className, ...props }: React.HTMLAttributes<HTMLHeadingElement>) => (
    <h2
      className={cn(
        "mt-10 scroll-m-20 border-b pb-1 text-3xl font-semibold tracking-tight first:mt-0",
        className
      )}
      {...props}
    />
  ),
  h3: ({ className, ...props }: React.HTMLAttributes<HTMLHeadingElement>) => (
    <h3
      className={cn(
        "mt-8 scroll-m-20 text-2xl font-semibold tracking-tight",
        className
      )}
      {...props}
    />
  ),
  h4: ({ className, ...props }: React.HTMLAttributes<HTMLHeadingElement>) => (
    <h4
      className={cn(
        "mt-8 scroll-m-20 text-xl font-semibold tracking-tight",
        className
      )}
      {...props}
    />
  ),
  p: ({ className, ...props }: React.HTMLAttributes<HTMLParagraphElement>) => (
    <p
      className={cn("leading-7 [&:not(:first-child)]:mt-6", className)}
      {...props}
    />
  ),
  ul: ({ className, ...props }: React.HTMLAttributes<HTMLUListElement>) => (
    <ul className={cn("my-6 ml-6 list-disc", className)} {...props} />
  ),
  ol: ({ className, ...props }: React.HTMLAttributes<HTMLOListElement>) => (
    <ol className={cn("my-6 ml-6 list-decimal", className)} {...props} />
  ),
  li: ({ className, ...props }: React.HTMLAttributes<HTMLElement>) => (
    <li className={cn("mt-2", className)} {...props} />
  ),
  blockquote: ({ className, ...props }: React.HTMLAttributes<HTMLElement>) => (
    <blockquote
      className={cn(
        "mt-6 border-l-2 pl-6 italic [&>*]:text-muted-foreground",
        className
      )}
      {...props}
    />
  ),
  pre: ({ className, ...props }: React.HTMLAttributes<HTMLPreElement>) => (
    <pre
      className={cn(
        "font-mono text-[13px] !p-4 !m-0 bg-transparent overflow-x-auto [counter-reset:line]",
        className
      )}
      {...props}
    />
  ),
  code: ({ className, ...props }: React.HTMLAttributes<HTMLElement> & { "data-language"?: string }) => {
    // If it has data-language, it's generated by rehype-pretty-code inside a <pre>
    const isInline = !props["data-language"];
    return (
      <code
        className={cn(
          isInline && "relative rounded bg-muted px-[0.3rem] py-[0.2rem] font-mono text-[13px]",
          !isInline && "grid min-w-full break-words rounded-none border-0 bg-transparent p-0 text-[13px]",
          className
        )}
        {...props}
      />
    )
  },
  Callout,
  Tabs: ({ className, ...props }: React.ComponentProps<typeof Tabs>) => (
    <Tabs className={cn("relative mt-6 w-full", className)} {...props} />
  ),
  TabsList: ({ className, ...props }: React.ComponentProps<typeof TabsList>) => (
    <TabsList className={cn("w-full justify-start rounded-none border-b bg-transparent p-0", className)} {...props} />
  ),
  TabsTrigger: ({ className, ...props }: React.ComponentProps<typeof TabsTrigger>) => (
    <TabsTrigger
      className={cn(
        "relative h-9 rounded-none border-b-2 border-b-transparent bg-transparent px-4 pb-3 pt-2 font-semibold text-muted-foreground shadow-none transition-none data-[state=active]:border-b-primary data-[state=active]:text-foreground data-[state=active]:shadow-none",
        className
      )}
      {...props}
    />
  ),
  TabsContent: ({ className, ...props }: React.ComponentProps<typeof TabsContent>) => (
    <TabsContent
      className={cn(
        "relative [&_h3.font-heading]:text-base [&_h3.font-heading]:font-semibold",
        className
      )}
      {...props}
    />
  ),
  figure: ({ className, children, ...props }: React.HTMLAttributes<HTMLElement> & { "data-rehype-pretty-code-figure"?: string }) => {
    if (!("data-rehype-pretty-code-figure" in props)) {
      return <figure className={cn("m-0 p-0", className)} {...props}>{children}</figure>;
    }
    
    let title = "";
    let preElement: React.ReactNode = null;
    
    React.Children.forEach(children, (child) => {
      if (React.isValidElement(child)) {
        const childProps = child.props as any;
        if (childProps["data-rehype-pretty-code-title"] !== undefined) {
          title = childProps.children as string;
        } else if (child.type === "pre") {
          preElement = child;
        }
      }
    });

    if (!preElement) {
       preElement = children;
    }

    const language = React.isValidElement(preElement) ? (preElement.props as any)["data-language"] : "";
    const rawCode = extractText(preElement);

    if (language === "mermaid") {
      return <Mermaid chart={rawCode} />;
    }
    
    return (
      <div data-rehype-pretty-code-figure="" className="relative my-6 overflow-hidden rounded-xl border border-[var(--code-border)] shadow-xl">
        {/* Header bar */}
        <div className="flex items-center justify-between bg-[var(--code-header)] px-4 py-2.5 border-b border-[var(--code-border)]">
          <div className="flex items-center gap-3">
            {/* Mac-style window controls */}
            <div className="flex gap-1.5">
              <div className="h-2.5 w-2.5 rounded-full bg-red-500/80" />
              <div className="h-2.5 w-2.5 rounded-full bg-yellow-500/80" />
              <div className="h-2.5 w-2.5 rounded-full bg-green-500/80" />
            </div>
            
            {/* Language badge */}
            {language && (
              <div className="text-[10px] font-bold tracking-widest text-[var(--code-muted)] uppercase">
                {language}
              </div>
            )}
          </div>
          
          <CopyButton value={rawCode} />
        </div>
        
        {/* Code content */}
        <div className="overflow-x-auto text-sm leading-6 bg-[var(--code-bg)] font-mono [&_pre]:!p-4 [&_pre]:!m-0 [&_pre]:!rounded-none [&_pre]:!border-0">
          {preElement}
        </div>
      </div>
    );
  },
  Icon,
}
